#!/bin/bash

# #script will fail and exit if any command fails
# set -o errexit

# # script will fail and exit when a pipe comamnd fails
# set -o pipefail

# #exit when uninitialised variable is used
# set -o nounset

python3 manage.py migrate --no-input
python3 manage.py collectstatic --no-input
python3 manage.py runserver 0.0.0.0:8000